apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: U3MxMV9kZGQ=
  MYSQL_DATABASE: dGVhY2g=
  MYSQL_USER: YWRtaW5fdXNlcg==
  MYSQL_PASSWORD: U3MxMV9kZGQ=
